config/routes.rb
Rails.application.routes.draw do
  root 'albums#index'

  resources :albums do
    resources :pictures, only: [:show, :new, :create, :edit, :update]
  end
end

app/models/album.rb
class Album < ApplicationRecord
  has_many :pictures, dependent: :nullify

  validates :title, presence: true,
                    uniqueness: { case_sensitive: false }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/character.rb
class Character < ApplicationRecord
  has_many :locations, dependent: :destroy
  has_many :pictures, through: :locations
  has_and_belongs_to_many :scores

  has_one_attached :avatar

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false },
                   length: { maximum: 24 }

end

app/models/location.rb
class Location < ApplicationRecord
  belongs_to :picture
  belongs_to :character

  attr_accessor :coords

  validates :x_coord, presence: true
  validates :y_coord, presence: true
  validate :unique_local_coords

  def coords
    [x_coord, y_coord]
  end

  def coords=(array)
    update(x_coord: array[0], y_coord: array[1])
  end

  private

    def unique_local_coords
      if other_character = picture.characters.where.not(id: id).where('x_coord = ?', x_coord).where('x_coord = ?', x_coord).first
        errors.add(:coords, "are already taken")
      end
    end

end

app/models/picture.rb
class Picture < ApplicationRecord
  belongs_to :album, optional: true
  has_many :locations, dependent: :destroy
  has_many :characters, through: :locations
  has_many :scores, dependent: :destroy

  has_one_attached :image

  validates :title, presence: true,
                    uniqueness: { case_sensitive: false },
                    length: { maximum: 32 }

end

app/models/score.rb
class Score < ApplicationRecord
  belongs_to :user
  belongs_to :picture
  has_and_belongs_to_many :characters
end

app/models/user.rb
class User < ApplicationRecord
  has_many :scores, dependent: :destroy

  validates :name, presence: true,
                   uniqueness: { case_sensitive: false }

  has_secure_password
  validate :none_or_both_passwords

  def self.digest string
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST : BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  def authenticates? attribute, token
    digest = send("#{attribute}_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest) # what is this for???
    BCrypt::Password.new(digest).is_password?(token)
  end

  private

    def none_or_both_passwords
      if password.present? && password_confirmation.nil?
        errors.add(:password_confirmation, "must be present to confirm")
      end
    end
end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController
  before_action :require_login, except: [:index, :show]
  before_action :require_admin, except: [:index, :show]

  before_action :set_album, only: [:show, :edit, :update, :destroy]
  before_action :set_pictures, only: [:show, :edit]

  def index
    @albums = Album.all
  end

  def show
  end

  def new
    @album = Album.new
  end

  # def edit
  # end

  def create
    @album = Album.new(album_params)

    respond_to do |format|
      if @album.save
        format.html { redirect_to @album, notice: 'Album was successfully created.' }
        format.json { render :show, status: :created, location: @album }
      else
        format.html { render :new }
        format.json { render json: @album.errors, status: :unprocessable_entity }
      end
    end
  end

  # def update
  #   respond_to do |format|
  #     if @album.update(album_params)
  #       format.html { redirect_to @album, notice: 'Album was successfully updated.' }
  #       format.json { render :show, status: :ok, location: @album }
  #     else
  #       format.html { render :edit }
  #       format.json { render json: @album.errors, status: :unprocessable_entity }
  #     end
  #   end
  # end

  # def destroy
  #   @album.destroy
  #   respond_to do |format|
  #     format.html { redirect_to albums_url, notice: 'Album was successfully destroyed.' }
  #     format.json { head :no_content }
  #   end
  # end

  private
    def set_album
      @album = Album.find(params[:id])
    end

    def set_pictures
      @pictures = @album.pictures
    end

    def album_params
      params.require(:album).permit(:title)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def require_login
    raise "TODO"
  end

  def require_admin
    raise "TODO"
  end

end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController

  def index
    @pictures = Picture.all
  end

  def show
    @picture = Picture.find(params[:id])
  end

end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/albums/_form.html.erb
<%= form_for @album do |f| %>

  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <%= f.submit %>

<% end %>

app/views/albums/index.html.erb
<h2>Albums</h2>

<% if @albums.any? %>

  <% @albums.each do |album| %>

    <h3><%= link_to album.title, album_path(album) %></h3>

  <% end %>

<% else %>

  <p>No albums have been created yet...</p>

<% end %>

app/views/albums/new.html.erb
<h2>Create A New Album</h2>

<%= render 'form' %>

app/views/albums/show.html.erb
<%= tag.h2 @album.title %>

<% if @pictures.any? %>

  <% @pictures.each do |picture| %>

    <h3><%= link_to picture.title, album_picture_path(@album, picture) %></h3>

  <% end %>

<% else %>

  <p>No pictures have been added to the album yet...</p>

<% end %>

app/views/application/_flashes.html.erb
<% if flash.any? %>

  <ul class="flash">

    <% flash.each do |key, message| %>

      <%= tag.li message, class: key %>

    <% end %>

  </ul>

  <hr />

<% end %>

app/views/application/_header.html.erb
<h1>Where's Waldo</h1>

<hr />

<%= render 'flashes' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WheresWaldo</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= yield :head %>
  </head>

  <body>
    <%= render 'header' %>
    <%= yield %>
  </body>
</html>

app/views/pictures/show.html.erb
<%= tag.h2 @picture.title %>

<div id='vm'>
  <p>{{ JAVASCRIPT }}</p>
</div>